#filebeat.inputs:
#  - type: log
#    paths:
#      - /var/lib/docker/containers/*/*.log
#    json.message_key: log.message
#    json.keys_under_root: true
#output.logstash:
#  hosts: ["logstash:5000"]
#filebeat.inputs:
#- type: log
#  paths:
#    - /var/log/nginx/*.log
#
#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log
#      - /logging/django.log
#filebeat.inputs:
#- type: docker
#  containers:
#    stream: "all"
#    ids:
#      - '*'
#    condition.contains:
#      docker.container.name: "nextpage-nginx"

logging.level: debug


output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "nextpage"