version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - t4y

  backend:
    container_name: backend
    build: ./backend
    command: sh -c "python manage.py makemigrations account && \
      python manage.py makemigrations chart && \
      python manage.py makemigrations search && \
      python manage.py makemigrations subscribe && \
      python manage.py makemigrations summary && \
      python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbit
    networks:
      - t4y



  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - t4y


  celery:
    container_name: celery
    build: ./backend
    command: 'celery -A summary.celery worker --loglevel="info"'
    depends_on:
      - rabbit
      - db
    networks:
      - t4y
    volumes:
      - ./backend:/usr/src/app
    environment:
    - CELERY_BROKER_URL = 'amqp://admin:mypass@rabbit:5672'


  worker:
    container_name: worker
    build: './backend/worker'
    user: nobody
    depends_on:
      - rabbit
      - celery
    environment:
    - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672
    volumes:
      - ./backend:/usr/src/app
    networks:
    - t4y




networks:
  t4y:
    driver: bridge
