global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

  external_labels:
    monitor: 'codelab-monitor'
    query_log_file: query_log_file.log

rule_files:
  - "rule.yml"

scrape_configs:
  - job_name: 'monitoring-item'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'

    static_configs:
      - targets: ['backend:8000', 'prometheus:9090', 'db:5432', 'node_exporter:9100', 'cadvisor:8080']
        labels:
          service: 'monitor'
