name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd 2023WB-Team-N
            git checkout main
            git pull origin main
            docker-compose down
            docker container prune
            docker rm -f $(docker ps -qa)
            docker image prune
            docker rmi $(docker images -q)
            docker-compose up --build
